# Generated by Django 3.2 on 2022-04-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flairsou_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='flairsou_api_account_unique_name_in_parent_and_book',
        ),
    ]
