# Generated by Django 4.0.4 on 2022-07-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "flairsou_api",
            "0002_remove_account_flairsou_api_account_unique_name_in_parent_and_book",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="invoice",
        ),
    ]
