# Generated by Django 4.0.4 on 2022-07-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flairsou_api", "0003_remove_transaction_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        editable=False,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.FileField(
                        null=True, upload_to="uploads/", verbose_name="Document"
                    ),
                ),
                ("notes", models.TextField(null=True, verbose_name="Notes")),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flairsou_api.transaction",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
