name: Django CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - '*.py'
      - 'Pipfile*'
      - '.style.yapf'
      - 'test.sh'
      - 'flairsou/**'
      - 'flairsou_api/**'
      - 'flairsou_frontend/**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '*.py'
      - 'Pipfile*'
      - '.style.yapf'
      - 'test.sh'
      - 'flairsou/**'
      - 'flairsou_api/**'
      - 'flairsou_frontend/**.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Lint using flake8
        uses: huetremy/lintly-flake8-github-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      #- name: Black Check
      #  uses: jpetrucciani/black-check@20.8b1
        
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Copy config_template file
        run: cp flairsou/config_template.py flairsou/config.py

      - name: Install pipenv
        run: python3 -m pip install pipenv

      - name: Pipenv sync
        run : pipenv sync
          
      - name: Run pipenv test script
        run : pipenv run test
