name: Flairsou-CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  changed-files:
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    name: "Getting changed files"
    steps:
      - name: "Get backend changed files"
        id: changed-backend-files
        uses: tj-actions/changed-files@v2.1
        with:
          files: |
            *.py
            Pipfile*
            .style.yapf
            test.sh
            flairsou/**
            flairsou_api/**
            flairsou_frontend/**.py
      - name: "Get frontend changed files"
        id: changed-frontend-files
        uses: tj-actions/changed-files@v2.1
        with:
          files: |
            flairsou_frontend/**
          files_ignore: |
            flairsou_frontend/**.py
            flairsou_frontend/templates/**
            flairsou_frontend/static/**
            flairsou_frontend/migrations/**
    outputs:
      frontend-changed: ${{ steps.changed-frontend-files.outputs.any_changed }}
      backend-changed: ${{ steps.changed-backend-files.outputs.any_changed }}

  npm-build:
    name: "Build Frontend"
    needs:
      - changed-files
    if: ${{ needs.changed-files.frontend-changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install deps
        run: npm install
        working-directory: flairsou_frontend
      - name: Dev build
        run: npm run build-dev
        working-directory: flairsou_frontend
      - name: Prod build
        run: npm run build
        working-directory: flairsou_frontend


  api-test:
    name: "Test API"
    needs:
      - changed-files
    if: ${{ needs.changed-files.backend-changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy config_template file
        run: cp flairsou/config_template.py flairsou/config.py
      - name: Install pipenv
        run: python3 -m pip install pipenv
      - name: Pipenv sync
        run : pipenv sync
      - name: Run pipenv test script
        run : pipenv run test